setono_sylius_catalog_promotion_admin_promotion:
    resource: |
        alias: setono_sylius_catalog_promotion.promotion
        path: catalog-promotions
        section: admin
        templates: '@SyliusAdmin\\Crud'
        except: ['show']
        redirect: update
        grid: setono_sylius_catalog_promotion_admin_promotion
        permission: true
        vars:
            all:
                subheader: setono_sylius_catalog_promotion.ui.manage_promotions
                templates:
                    form: "@SetonoSyliusCatalogPromotionPlugin/Admin/Promotion/_form.html.twig"
            index:
                icon: in cart
            update:
                templates:
                    form: "@SetonoSyliusCatalogPromotionPlugin/Admin/Promotion/_form.html.twig"
    type: sylius.resource
